name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

permissions:
  contents: write  # Permission to write to the repository

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Make sure `sphinx` and other dependencies are listed here

      # Step 4: Build the Sphinx documentation
      - name: Build Documentation
        run: sphinx-build -b html docs/ docs/_build/  # Generates HTML in docs/_build/

      # Step 5: List the contents of the build folder (for debugging)
      - name: List files in build folder
        run: ls -R docs/_build/  # This will show all files generated in the build folder

      # Step 6: Move Built Docs to Root (without clearing root)
      - name: Move Built Docs to Root
        run: |
          cp -R docs/_build/*.html .  # Copy all files from docs/_build/html to the root

      # Step 7: Commit and push the changes to GitHub
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .  # Stage the moved files
          git commit -m "Deploy documentation" || echo "No changes to commit"
          git push
